FROM ghcr.io/puppeteer/puppeteer:23.4.0

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /usr/src/app

COPY Backend/package.json Backend/package-lock.json ./

RUN npm ci

COPY . .

CMD ["node", "index.js"]
